### ISSUE TITLE
Menu Item Font - Serif?

### ISSUE THREAD

**Issue by m9aertner** [pfadfinder-konstanz/hugo-dpsg#4]
Is it _intentional_ that the Menu Items appear in a *serif font* when the site default is sans serif?

Please consider `themes\hugo-dpsg\assets\css\style.css # .menu__link`:
- Line 3/5 has `$fontSans / $fontFamilyPrimary` as `"Open Sans", Helvetica, Arial, sans-serif`
- Line 633 shows "'Merriweather', Georgia, serif;"
- Line 450 similar with "address", hard-coded (but visually fine).

I would _expect_ that a theme does not mix serif and sans-serif. I realize that custom CSS files can be configured to override this, and you of course might simply find the current look much better, but from a (non-professional) design point of view I believe the default should be _consistent_ across the whole page, i.e. non-serif.

Feel free to close this issue if that choice was intentional. Also, I did not check the underlying WordPress theme, maybe that's just a setting that was taken over from there faithfully. Otherwise, just deleting CSS line 633 is what I would recommend.

I really appreciate you making your work available publicly. Thanks!
M.

**Comment by mxmehl** [comment]
Yes, it's intentional in a sense that the same fonts are used on [dpsg.de](https://dpsg.de/). The headlines in my theme differ a bit (sans instead of serif), but mixing these seemed even less logical to me.

> I really appreciate you making your work available publicly. Thanks!

Thank you, and thanks for reporting this issue :)
