### ISSUE TITLE
Add to awesome-dpsg list

### ISSUE THREAD

**Issue by mstoetzer** [pfadfinder-konstanz/hugo-dpsg#9]
Hi, ich sammle gerade diverse Tools und anderes und möchte euer Repo gerne auf http://github.com/mstoetzer/awesome-dpsg verlinken. :)

**Comment by mxmehl** [comment]
Danke, sehr gerne! Ich bin gespannt, was noch auf der Liste erscheinen wird :)

Schließt du das Issue, wenn du das Repo dort drin hast?

**Comment by mstoetzer** [comment]
Habs hinzufügt: https://github.com/mstoetzer/awesome-dpsg/blob/main/README.md#design-and-themes

ToC fehlt noch und mit der Zeit wächst die Struktur mit Kategorien und so. Gerne contributen :)

Lasercutter und Egg-Bot Files verlinke ich demnächst auch
